# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17e8072fa9a04ee3110cfad093cd351bd253a5bfe58cc9c3a1b9508ff93a5e61c8a3901e950834ff408e18b5475c3032880e8b359be4fea81c4eec0178e38745

test:
  secret_key_base: 1ac1ae55ac98336299fd83cd85449232ca43052295899c9ed9e3db6cb7a681d529c600313bea841f9db38eaf20b998d05524abcefb3e4eff78e1faf748d79e20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
